CREATE USER  vanessa PASSWORD '1234';
GRANT CONNECT ON DATABASE desenv TO  vanessa ;
GRANT USAGE ON SCHEMA tratamento TO  vanessa ;
GRANT SELECT ON ALL TABLES IN SCHEMA tratamento TO  vanessa ;
GRANT SELECT, UPDATE, DELETE, INSERT ON ALL TABLES IN SCHEMA tratamento TO  vanessa ;
GRANT SELECT on tratamento.vw_menu_princ_tratamento TO vanessa ;
GRANT SELECT on tratamento.vw_menu_princ_tratamento_usua TO  vanessa ;
GRANT SELECT on tratamento.vw_menu_princ_usua TO  vanessa ;
GRANT SELECT, UPDATE, INSERT, DELETE ON tratamento.tb_c_grupo_acesso TO  vanessa ;
GRANT SELECT, UPDATE, INSERT, DELETE ON tratamento.tb_c_grupo_usua_acesso TO  vanessa ;
GRANT SELECT, UPDATE, INSERT, DELETE ON tratamento.tb_c_grupo_usua_menu_sist_tratamento TO  vanessa ;
GRANT SELECT, UPDATE, INSERT, DELETE ON tratamento.tb_c_menu_sist_tratamento TO  vanessa ;
GRANT SELECT, UPDATE, INSERT, DELETE ON tratamento.tb_c_usua_acesso TO  vanessa ;
GRANT DELETE, UPDATE, INSERT, SELECT ON tratamento.tb_c_log_acesso TO  vanessa ;
GRANT SELECT ON  TABLE tratamento.vw_menu_princ_tratamento TO vanessa ;
GRANT SELECT ON  TABLE tratamento.vw_menu_princ_tratamento_usua TO vanessa ;
GRANT SELECT ON  TABLE tratamento.vw_menu_princ_usua TO  vanessa ;
GRANT SELECT ON SEQUENCE tratamento.sq_log_acesso TO vanessa ;
GRANT SELECT ON SEQUENCE tratamento.sq_acesso_transac_tratamento TO vanessa ;
GRANT SELECT ON SEQUENCE tratamento.sq_grupo_usua_acesso TO vanessa ;
GRANT SELECT ON SEQUENCE tratamento.sq_grupo_usua_menu_sist_tratamento TO vanessa ;
GRANT SELECT ON SEQUENCE tratamento.sq_grupo_usua_transac_acesso TO vanessa ;
GRANT SELECT ON SEQUENCE tratamento.sq_log_acesso TO vanessa ;
GRANT SELECT ON SEQUENCE tratamento.sq_menu_sist_tratamento TO vanessa ;
GRANT SELECT ON SEQUENCE tratamento.sq_usua_acesso TO vanessa ;
GRANT SELECT ON SEQUENCE tratamento.sq_equipe TO vanessa ;
GRANT SELECT ON SEQUENCE tratamento.sq_status_equipe TO vanessa ;
GRANT SELECT ON SEQUENCE tratamento.sq_status_equipe TO vanessa ;
GRANT SELECT ON SEQUENCE tratamento.sq_pnel_solic_trtmto TO vanessa ;
GRANT SELECT, UPDATE, INSERT, DELETE ON tratamento.tb_c_local_trtmto TO  vanessa ;
GRANT SELECT ON SEQUENCE tratamento.sq_local_trtmto TO vanessa ;
GRANT SELECT, UPDATE, INSERT, DELETE ON tratamento.tb_c_status_trtmto TO  vanessa ;
GRANT SELECT ON SEQUENCE tratamento.sq_status_trtmto TO vanessa ;
GRANT SELECT, UPDATE, INSERT, DELETE ON tratamento.tb_c_risco_pcnt TO  vanessa ;
GRANT SELECT ON SEQUENCE tratamento.sq_risco_pcnt TO vanessa ;
